language: ruby
script: "bundle exec rake test"
cache: bundler
rvm:
  - '2.7.2'
  - '2.6.6'
  - '2.5.8'
  - '2.4.10'
  - '2.3.8'
  - '2.2.10'
  - '2.1.10'

gemfile:
  - gemfiles/am_3_2.gemfile
  - gemfiles/am_4_0.gemfile
  - gemfiles/am_4_1.gemfile
  - gemfiles/am_4_2.gemfile

notifications:
  email: false
