language: ruby
script: "bundle exec rake test"
cache: bundler
sudo: false
rvm:
  - '2.4.3'
  - '2.3.6'
  - '2.2.9'
  - '2.1.10'

gemfile:
  - gemfiles/am_3_2.gemfile
  - gemfiles/am_4_0.gemfile
  - gemfiles/am_4_1.gemfile
  - gemfiles/am_4_2.gemfile

notifications:
  email: false
